// Code generated by goyacc -o parser_generated.go -p yy grammar.y. DO NOT EDIT.

//line grammar.y:2
package dsl

import __yyfmt__ "fmt"

//line grammar.y:2

import (
	"fmt"
)

//line grammar.y:9
type yySymType struct {
	yys   int
	expr  *Expression
	exprs []*Expression
	str   string
	num   float64
}

const IDENTIFIER = 57346
const STRING = 57347
const NUMBER = 57348
const DOT = 57349
const LPAREN = 57350
const RPAREN = 57351
const LBRACKET = 57352
const RBRACKET = 57353
const COMMA = 57354
const PLUS = 57355
const MINUS = 57356
const MULTIPLY = 57357
const DIVIDE = 57358
const MODULO = 57359
const EQ = 57360
const NE = 57361
const LT = 57362
const LE = 57363
const GT = 57364
const GE = 57365
const AND = 57366
const OR = 57367
const NOT = 57368
const TRUE = 57369
const FALSE = 57370
const UMINUS = 57371

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"NUMBER",
	"DOT",
	"LPAREN",
	"RPAREN",
	"LBRACKET",
	"RBRACKET",
	"COMMA",
	"PLUS",
	"MINUS",
	"MULTIPLY",
	"DIVIDE",
	"MODULO",
	"EQ",
	"NE",
	"LT",
	"LE",
	"GT",
	"GE",
	"AND",
	"OR",
	"NOT",
	"TRUE",
	"FALSE",
	"UMINUS",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line grammar.y:322

// Helper function to convert expression to string for Args field
// This maintains compatibility with the existing Expression struct
func exprToString(expr *Expression) string {
	if expr == nil {
		return ""
	}

	switch expr.Type {
	case ExprLiteral:
		return expr.Path

	case ExprPath:
		return expr.Path

	case ExprBinary:
		left := exprToString(expr.Left)
		right := exprToString(expr.Right)
		return left + " " + expr.Operator + " " + right

	case ExprUnary:
		operand := exprToString(expr.Operand)
		return expr.Operator + operand

	case ExprFunction:
		args := ""
		for i, arg := range expr.Args {
			if i > 0 {
				args += ", "
			}
			args += arg
		}
		return expr.Function + "(" + args + ")"

	case ExprArrayIndex:
		index := exprToString(expr.Index)
		return expr.Path + "[" + index + "]"

	default:
		return fmt.Sprintf("<expr:%d>", expr.Type)
	}
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 146

var yyAct = [...]int8{
	2, 63, 19, 20, 21, 22, 23, 32, 33, 26,
	27, 28, 29, 36, 19, 20, 21, 22, 23, 64,
	41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
	51, 52, 53, 21, 22, 23, 55, 57, 54, 37,
	60, 61, 65, 1, 19, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 30, 31, 38, 39, 34,
	40, 58, 35, 59, 62, 66, 19, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 30, 31, 56,
	9, 8, 11, 19, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 29, 30, 31, 19, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 30, 31, 18,
	13, 14, 17, 12, 10, 4, 3, 5, 0, 7,
	19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
	29, 6, 15, 16, 19, 20, 21, 22, 23, 24,
	25, 26, 27, 28, 29, 30,
}

var yyPact = [...]int16{
	105, -1000, 83, -1000, -1000, -1000, 105, 105, -1000, 52,
	-1000, -1000, 105, -1000, -1000, -1000, -1000, 35, 50, 105,
	105, 105, 105, 105, 105, 105, 105, 105, 105, 105,
	105, 105, -1000, -1000, 34, 105, 70, -1000, 33, 105,
	105, 18, 18, -1000, -1000, -1000, -11, -11, 1, 1,
	1, 1, 107, 121, -1000, 53, -1000, -1000, -8, 7,
	83, 31, -1000, -1000, 105, -1000, 83,
}

var yyPgo = [...]int8{
	0, 0, 117, 116, 115, 114, 82, 81, 80, 63,
	61, 43,
}

var yyR1 = [...]int8{
	0, 11, 1, 1, 1, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
	2, 2, 2, 2, 2, 8, 8, 8, 8, 5,
	6, 6, 7, 7, 7, 7, 10, 10, 9, 9,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 2,
	1, 1, 1, 1, 3, 2, 3, 1, 3, 4,
	4, 4, 1, 1, 1, 1, 0, 1, 1, 3,
}

var yyChk = [...]int16{
	-1000, -11, -1, -3, -4, -2, 26, 14, -7, -8,
	-5, -6, 8, 5, 6, 27, 28, 7, 4, 13,
	14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
	24, 25, -1, -1, 7, 10, -1, 4, 7, 8,
	10, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, 4, -1, 9, 4, -10, -9,
	-1, -1, 11, 9, 12, 11, -1,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 4, 0, 0, 20, 21,
	22, 23, 0, 32, 33, 34, 35, 0, 27, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 18, 19, 0, 0, 0, 25, 0, 36,
	0, 5, 6, 7, 8, 9, 10, 11, 12, 13,
	14, 15, 16, 17, 26, 0, 24, 28, 0, 37,
	38, 0, 30, 29, 0, 31, 39,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:40
		{
			yylex.(*Lexer).result = yyDollar[1].expr
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:53
		{
			// Check if it's string concatenation or arithmetic
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "+",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:63
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "-",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:72
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "*",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:81
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "/",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:90
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "%",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:99
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "==",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:108
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "!=",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:117
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "<",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:126
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "<=",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:135
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: ">",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:144
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: ">=",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:153
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "&&",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:162
		{
			yyVAL.expr = &Expression{
				Type:     ExprBinary,
				Operator: "||",
				Left:     yyDollar[1].expr,
				Right:    yyDollar[3].expr,
			}
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:174
		{
			yyVAL.expr = &Expression{
				Type:     ExprUnary,
				Operator: "!",
				Operand:  yyDollar[2].expr,
			}
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:182
		{
			yyVAL.expr = &Expression{
				Type:     ExprUnary,
				Operator: "-",
				Operand:  yyDollar[2].expr,
			}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:197
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:204
		{
			yyVAL.expr = &Expression{
				Type: ExprPath,
				Path: "." + yyDollar[2].str,
			}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:211
		{
			yyVAL.expr = &Expression{
				Type: ExprPath,
				Path: yyDollar[1].expr.Path + "." + yyDollar[3].str,
			}
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:218
		{
			yyVAL.expr = &Expression{
				Type: ExprPath,
				Path: yyDollar[1].str,
			}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:225
		{
			yyVAL.expr = &Expression{
				Type: ExprPath,
				Path: yyDollar[1].str + "." + yyDollar[3].str,
			}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:235
		{
			args := make([]string, len(yyDollar[3].exprs))
			for i, expr := range yyDollar[3].exprs {
				// Convert expression back to string for compatibility
				// This is a simplification - in practice you'd evaluate or store the expression
				args[i] = exprToString(expr)
			}
			yyVAL.expr = &Expression{
				Type:     ExprFunction,
				Function: yyDollar[1].str,
				Args:     args,
			}
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:252
		{
			yyVAL.expr = &Expression{
				Type:  ExprArrayIndex,
				Path:  yyDollar[1].expr.Path,
				Index: yyDollar[3].expr,
			}
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:260
		{
			yyVAL.expr = &Expression{
				Type:  ExprArrayIndex,
				Path:  yyDollar[1].str,
				Index: yyDollar[3].expr,
			}
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:271
		{
			yyVAL.expr = &Expression{
				Type: ExprLiteral,
				Path: yyDollar[1].str,
			}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:278
		{
			yyVAL.expr = &Expression{
				Type: ExprLiteral,
				Path: fmt.Sprintf("%v", yyDollar[1].num),
			}
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:285
		{
			yyVAL.expr = &Expression{
				Type: ExprLiteral,
				Path: "true",
			}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:292
		{
			yyVAL.expr = &Expression{
				Type: ExprLiteral,
				Path: "false",
			}
		}
	case 36:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:302
		{
			yyVAL.exprs = []*Expression{}
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:306
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:313
		{
			yyVAL.exprs = []*Expression{yyDollar[1].expr}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:317
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	}
	goto yystack /* stack new state and value */
}
