apiVersion: platform.example.com/v1alpha1
kind: WebService
metadata:
  name: nginx-app
  namespace: default
spec:
  image: nginx:1.25
  replicas: 3
  port: 80
  enableHA: true
  resources:
    cpu: "100m"
    memory: "128Mi"

